<?php

namespace App\Http\Requests\Api\User\Address;

use App\Http\Requests\Api\MasterApiFormRequest;

class StoreAddressValid extends MasterApiFormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'address'       => 'required|string',
            'latitude'      => 'required',
            'longitude'     => 'required',
            'notes'         => 'sometimes|string',
            'is_default'    => 'sometimes|boolean'
        ];
    }

    public function validated()
    {
        $data =  parent::validated(); // TODO: Change the autogenerated stub
        $data['is_default'] = $this->is_default ? : 0;

        return collect($data)->toArray();
    }
}
