<?php

namespace App\Http\Requests\Website\Product;

use Illuminate\Foundation\Http\FormRequest;

class ProductUpdateValid extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name:ar'             => 'required' ,
            'name:en'             => 'required' ,
            'description:ar'      => 'required' ,
            'description:en'      => 'required' ,
            'category_id'         => 'nullable|exists:categories,id',
            'brand_id'            => 'required|exists:brands,id',
            'frame_material_id'   => 'required|exists:frame_materials,id',
            'age_id'              => 'required|exists:ages,id',
            'frame_shap_id'       => 'required|exists:frame_shaps,id',
            'product_type_id'     => 'required|exists:product_types,id',
            'price'               => 'required|numeric'  ,
            'quantity'            => 'required|numeric'  ,

            'frame_color_id'    => 'required|array',
            'lens_color_id'     => 'required|array',
            'frame_color_id.*'  => 'exists:colors,id',
            'lens_color_id.*'   => 'exists:colors,id',

            'image'               => 'nullable|mimes:jpeg,png,jpg|image|max:10240',
            'images.*'            => 'nullable|mimes:jpeg,png,jpg|image|max:10240',

            'additional_data'    => 'required|array',
            'additional_data.frame_height'      => 'required|string|max:100',
            'additional_data.temple_length'     => 'required|string|max:100',
            'additional_data.lens_width'        => 'required|string|max:100',
            'additional_data.nose_bridge'       => 'required|string|max:100',
        ];
    }

    public function messages()
    {
        return [
            'name:ar.required' => 'من فضلك مطلوب الإسم بالعربي',
            'name:en.required' => 'من فضلك مطلوب الإسم بالإنجليزي',
            'description:ar.required' => 'من فضلك مطلوب الوصف بالعربي',
            'description:en.required' => ' من فضلك مطلوب بالإنجليزي',
            'category_id.required' => 'من فضلك مطلوب القسم ',
            'brand_id.required' => 'من فضلك مطلوب الماركة',
            'frame_material_id.required' => 'من فضلك مطلوب الخامة',
            'age_id.required' => 'من فضلك مطلوب العمر',
            'frame_shap_id.required' => 'من فضلك مطلوب شكل الإطار',
            'product_type_id.required' => 'من فضلك مطلوب نوع المنتج',
            'price.required' => 'من فضلك مطلوب السعر',

            'frame_color_id.required'  => 'مطلوب لون الإطار',
            'lens_color_id.required'  => 'مطلوب لون العدسة',

            'quantity.required' => 'من فضلك مطلوب الكمية',
            'image.required' => 'من فضلك مطلوب صورة المنتج الرئيسية',

            'additional_data.frame_height.required'  => 'من فضلك مطلوب طول الاطار',
            'additional_data.temple_length.required'  => 'من فضلك مطلوب طول الزراع',
            'additional_data.lens_width.required'  => 'من فضلك مطلوب قطر العدسه',
            'additional_data.nose_bridge.required'  => 'من فضلك مطلوب مقصوره العدسه',
        ]; // TODO: Change the autogenerated stub
    }

    public function validated()
    {
        $data =  parent::validated(); // TODO: Change the autogenerated stub

        return collect($data)->except(['image','images','frame_color_id','lens_color_id'])->filter()->toArray();
    }
}
